[te_model]
name = 'TE identifier'
location = 'models/te_identifier.hdf5'
labels = ['TE', 'NonTE']

[class_model]
name = 'TE class identifier'
location = 'models/te_class.hdf5'
labels = ['DNA', 'Retro']

[retro_model]
name = 'LTR/non-LTR identifier'
location = 'models/retro.hdf5'
labels = ['LTR', 'nonLTR']

[dna_model]
name = 'Class 2 classifier'
location = 'models/dna_te.hdf5'
labels = ['CMC', 'Helitron', 'Novosib', 'Sola', 'Tc1-Mariner', 'Zator', 'hAT']

[ltr_model]
name = 'LTR classifier'
location = 'models/LTR.hdf5'
labels = ['Copia', 'ERV', 'Gypsy', 'Bel-Pao']

[nonltr_model]
name = 'non-LTR classifier'
location = 'models/nonLTR.hdf5'
labels = ['L1', 'CRE', 'DIRS', 'SINE']
